name: travel_manager
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  social_media_buttons: ^1.0.0
  google_fonts: ^6.2.1
  firebase_auth: ^5.3.3
  flutter_launcher_icons: ^0.14.3
  persistent_bottom_nav_bar: ^6.2.1
  provider: ^6.1.2
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.3
  path: ^1.9.0
  intl: ^0.19.0
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/image2/
    - assets/des_img/
    - assets/app_icon.png

    - assets/images/paris.jpg
    - assets/images/newyork.jpg
    - assets/images/tokyo.jpg
    - assets/images/rome.jpg
    - assets/images/sydney.jpg
    - assets/images/akshaysir.jpg

flutter_launcher_icons:
  android: "app_icon"
  ios: true
  image_path: "assets/image2/logo.jpg"
